--Session #1
BEGIN;
SHOW TRANSACTION ISOLATION LEVEL;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SHOW TRANSACTION ISOLATION LEVEL;
SELECT * FROM pizzeria WHERE name  = 'Pizza Hut';

--Session #2
BEGIN;
SHOW TRANSACTION ISOLATION LEVEL;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SHOW TRANSACTION ISOLATION LEVEL;
SELECT * FROM pizzeria WHERE name  = 'Pizza Hut';

--Session #1
UPDATE pizzeria
SET rating = 4
WHERE name = 'Pizza Hut';
COMMIT;

--Session #2
UPDATE pizzeria
SET rating = 3.6
WHERE name = 'Pizza Hut';
COMMIT;

--Session #1
SELECT * FROM pizzeria WHERE name  = 'Pizza Hut';

--Session #2
SELECT * FROM pizzeria WHERE name  = 'Pizza Hut';