--Session #1
BEGIN;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SHOW TRANSACTION ISOLATION LEVEL;

--Session #2
BEGIN;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SHOW TRANSACTION ISOLATION LEVEL;

--Session #1
SELECT SUM(rating) FROM pizzeria;

--Session #2
INSERT INTO pizzeria (id, name, rating)
SELECT 11, 'Kazan Pizza 2', 4;
COMMIT;

--Session #1
SELECT SUM(rating) FROM pizzeria;
COMMIT;

--Session #1
SELECT SUM(rating) FROM pizzeria;

--Session #2
SELECT SUM(rating) FROM pizzeria;